config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]

  resources :comments

  resources :chapters

  resources :sagas

  resources :users

    resources :sagas do
      resources :chapters
    end

  resources :chapters do
    resources :comments
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :sagas
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate,            except: [:new, :create]
  before_action :load_user,               except: [:index, :new, :create]
  # before_action :authorize_admin_only,    only:   :index
  # before_action :authorize_user_only,     only:   :show
  before_action :authorize_user_or_admin, except: [:index, :show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.sort.reverse.reject {|user| user == current_user}
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user = User.find(params[:id])
    @sagas = Saga.where("user_id = ?", params[:id])
    @chapters = Chapter.all
    @chapter = Chapter.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def password
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
     if @user.save
      log_in(@user)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      @user.update(user_params)
      redirect_to(user_path(session[:user_id]))
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      log_out!
      flash[:notice] = "Chao tam biet!"
      redirect_to(root_path)
    else #admin is deleting....
      @user.destroy
      redirect_to(users_path)
    end
  end

  def confirm_delete
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :about_me,
        :image_url,
        :gender,
        :city,
        :state,
        :country,
        :password
        )
    end

    def user_password_params
      @user_password_params ||= params.require(:user).permit(
        :old_password,
        :password,
        :password_confirmation
        )
    end

    def load_user
      @user = User.find_by(id: params[:id])
      redirect_to root_path if !@user
    end

    # def authorize_admin_only
    #   unless current_user.is_admin?
    #     redirect_to user_path(current_user)
    #   end
    # end

    def authorize_user_only
      unless current_user == @user
        redirect_to user_path(current_user)
      end
    end

    def authorize_user_or_admin
      unless current_user == @user || current_user.is_admin?
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :about_me %><br>
    <%= f.text_field :about_me %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password_digest %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<section class="main">
	<h1>Editing user</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</section>

app/views/users/index.html.erb
<section class="main">
  <h1>Listing users</h1>

  <table>
    <thead>
      <tr>
        <th>Image url</th>
        <th>Name</th>

        <th></th>

        <th></th>
        <th>City</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>State</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Country</th>
        <!-- <th colspan="3"></th> -->

    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><img src="<%= user.image_url %>"width="400" margin="50px"></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= link_to(user.name, user_path(user.id)) %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= user.city %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= user.state %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= user.country %></td>
          <td><%= link_to 'Show', user %></td>


        </tr>
      <% end %>
      <br>
    </tbody>
  </table>

  <br>


</section>

</section>

app/views/users/new.html.erb
<section class="main">
	<h1>New user</h1>

	<%= render 'form' %>

	<%= link_to 'Back', users_path %>
</section>

app/views/users/show.html.erb
<!-- <h1 style="color: red"><%= notice %></h1> -->

  <div class="container-fluid">
    <div class="row">
      <div class="user-bar col-md-12">
        <div class="col-md-3 user-squares">
          <p><i class="fa fa-home"></i></p>
            <li><%= link_to 'Home', user_path(session[:user_id]) %></li>
        </div>
        <div class="col-md-3 user-squares">
          <p><i class="fa fa-users"></i></p>
          <li><%= link_to "Meet Other Adventurers", users_path %></li>
        </div>
        <div class="col-md-3 user-squares">
          <% if @user.id == session[:user_id] %>
          <p><i class="fa fa-ship"></i></p>
            <li><%= link_to "Create New Saga", new_saga_path, class: "saga_build" %></li>
        </div>
        <div class="col-md-3 user-squares">
            <p><i class="fa fa-lightbulb-o"></i></p>
            <li><%= link_to "Get Some Ideas", chapters_path, class: "saga_build" %></li>
          <% end %>
         </div>
      </div>
    </div>

    <div class="row">
        <div class="profile-info col-md-10 col-centered">
          <div class="info-box col-md-6">
                <img id="profile-pic" src="<%= @user.image_url %>" width="200px">
              <ul id="profile-btns">
                  <% if @user.id == session[:user_id] %>
                    <li class="btn btn-default"><%= link_to 'Edit Profile', edit_user_path(@user) %></li><br>
                    <li class="btn btn-default"><%= link_to 'Delete Profile', user_path(session[:user_id]), method: :delete, data: { confirm: 'Are you sure you want to delete your profile?' } %></li>
                  <% end %>
              </ul>
            <div class="col-md-12">
              <li>
                <h3><strong>Name:</strong></h3>
                <p><%= @user.name %></p>
                <h3><strong>About me:</strong></h3>
                <p><%= @user.about_me %></p>
                <h3><strong>City:</strong></h3>
                <p><%= @user.city %></p>
            </div>
          </div>

          <div class="saga-box col-md-6">
             <h1>SAGAS</h1>
              <% if @sagas.length == 0 %>
                <p>You Don't Have any Sagas yet</p>
                <li id="new-saga" class="btn btn-default"><%=  link_to "Make one Now", new_saga_path %></li>
              <% else %>
                  <% @sagas.each do |saga| %> </br>
                  <%= link_to(saga.title, saga_path(saga.id), :id => "saga-title") %>
                      <% if current_user %>
                        <%= link_to 'Edit', edit_saga_path(saga.id), :class => "btn btn-default"  %>


                        <!-- Button trigger modal -->
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                              Add A Chapter
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                                  </div>
                                  <div class="modal-body">
                                    <%= form_for(@chapter) do |f| %>

                                        <div class="field">
                                          <%= f.label :title %><br>
                                          <%= f.text_field :title %>
                                        </div>
                                        <div class="field">
                                          <%= f.label :description %><br>
                                          <%= f.text_field :description %>
                                        </div>
                                        <div class="field">
                                          <%= f.label :image_url %><br>
                                          <%= f.text_field :image_url %>
                                        </div>
                                        <div class="field">
                                          <%= f.label :scope %><br>
                                          <%= f.text_field :scope %>
                                        </div>
                                        <div class="field">
                                          <%= f.label :tags %><br>
                                          <%= f.text_field :tags %>
                                        </div>
                                          <div class="field">
                                          <%= f.label :category %><br>
                                          <%= f.select(:category, [["Adreneline/Sport"], ["Milestones"], ["Travel"], ["Romance"], ["Food"], ["Education"], ["Culture"], ["Other"]]) %>
                                        </div><br>

                                        <div class="field">
                                        <%= f.hidden_field(:saga_id, :value => saga.id) %>
                                        </div>
                                        <div class="field">
                                        <%= f.hidden_field(:secret, :value => 'secret') %>
                                        </div>

                                  </div>
                                  <div class="modal-footer">
                                        <div class="actions">
                                          <%= f.submit class: "btn btn-default"  %>
                                        </div>
                                      <% end %>
                                  </div>
                                </div>
                              </div>
                            </div>
                        <br><br>
                      <% end %>
                        <% @chapters.each do |chapter| %>
                          <% if chapter.saga_id == saga.id %>
                            <div class="chapter-container">
                              <div class="image-container">
                                <img class="chapter" src="<%= chapter.image_url %>" width="50px">
                              </div>
                                <li><%= link_to(chapter.title, chapter_path(chapter.id), :id => "chapter-title") %></li>
                              </div>
                        <% end %>
                  <% end %>
              <% end %>
          <% end %>
          </div>
        </div>
     </div>






        <div class="right">


        <br/>



      </section>
      <section class="main">

      </section>
    </div>
</div>