config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]

  resources :comments

  resources :chapters

  resources :sagas

  resources :users

    resources :sagas do
      resources :chapters
    end

  resources :chapters do
    resources :comments
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :saga
  has_many :comments

    def add_tag_to_chapter(chapter_id, tag_string)
    # adds tags to a chapter either one at a time
    # or multiple tags as a string divided by commas
    # all tags are downcased to avoid search difficulties
    tag_string.downcase!
    self.tag_list.add(tag_string, parse: true)
    self.save
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
     user = User.find(session[:user_id])
     @chapters = Chapter.where(saga_id: nil)
     @sagas = Saga.where("user_id = ?", user.id)
     @chapter = Chapter.new
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    if session[:user_id] == nil
      redirect_to login_path
    else
      chapter = params[:id]
      @current_user = Saga.find(Chapter.find(chapter).saga_id).user_id
      @user = User.find(session[:user_id])
      @chapter_id = params[:id]
      @comments = Comment.where(user_id: @user.id, chapter_id: @chapter_id)
    end
  end

  # GET /chapters/new
  def new
    user = User.find(session[:user_id])
    sagas = Saga.where("user_id = ?", user.id)
    @sagas = sagas.select { |saga| saga.title }
    @saga_id = params[:saga_id]
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
    @saga_id = params[:saga_id]
  end

  # POST /chapters
  # POST /chapters.json
  def create
      if params[:chapter][:secret]
       chapter = Chapter.create(chapter_params)
      elsif
        params[:saga] == nil
        flash[:notice] = "You Don't have any Sagas. Create one Now!!!"
      else
      saga = Saga.find_by(title: params[:saga], user_id: session[:user_id])
      chapter = Chapter.create(chapter_params)
      saga_id = saga.id
      chapter.saga_id = saga_id
      chapter.save
    end
    redirect_to user_path(session[:user_id])
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    @chapter.update(chapter_params)
    redirect_to user_path(session[:user_id])
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    redirect_to user_path(session[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :description, :image_url, :scope, :tags, :category, :saga_id)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :scope %><br>
    <%= f.text_field :scope %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
    <div class="field">
    <%= f.label :category %><br>
    <%= f.select(:category, [["Adreneline/Sport"], ["Milestones"], ["Travel"], ["Romance"], ["Food"], ["Education"], ["Culture"], ["Other"]]) %>
  </div><br>

  <div class="field">
  <%= f.hidden_field(:saga_id, :value => @saga_id) %>
  </div>
  <div class="field">
  <%= f.hidden_field(:secret, :value => 'secret') %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<section class="main">
	<h1>Editing chapter</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @chapter %> |
	<%= link_to 'Back', chapters_path %>
</section>

app/views/chapters/index.html.erb
<section class="main">
  <h1>What Other Adventurers Are Doing</h1>
  <% @chapters.sample(9).each do |chapter| %>
  <div class="chapter_ideas">
  <%= chapter.title %>
   <br><br>
      <div class="thumb">
    <img src="<%= chapter.image_url %>">
  </div>
  <br>
    <%= form_for @chapter do |f| %>

    <label>"Choose A Saga"</label>
    <br><br>
    <select name="saga">
      <% @sagas.each do |saga| %>
      <option value="<%= saga.title %>"><%= saga.title %></option>
      <% saga = Saga.find_by(title: saga.title, user_id: session[:user_id]) %>
      <% @saga_id = saga.id %>

      <% end %>
    </select>
      <%= f.hidden_field(:title, :value => chapter.title) %>
      <%= f.hidden_field(:description, :value => chapter.description) %>
      <%= f.hidden_field(:image_url, :value => chapter.image_url) %>
      <%= f.hidden_field(:scope, :value => chapter.scope) %>
      <%= f.hidden_field(:tags, :value => chapter.tags) %>
      <%= f.hidden_field(:category, :value => chapter.category )%>
      <%= f.hidden_field(:saga_id, :value => @saga_id) %>
      <%= f.hidden_field(:chapter_id, :value => chapter.id) %>

      <br><br>
    <div class="actions">
      <%= f.submit "Add This Chapter" %>
    </div>
  <% end %>
  </div>
  <% end %>
</section>

app/views/chapters/new.html.erb
<section class="main">
	<h1>New chapter</h1>

	<%= render 'form' %>


	<%= link_to 'Back', user_path(session[:user_id]) %>
</section>

app/views/chapters/show.html.erb
<section class="main">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @chapter.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @chapter.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <img src="<%= @chapter.image_url %>" width="400">
  </p>

  <p>
    <strong>Scope:</strong>
    <%= @chapter.scope %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= @chapter.tags %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @chapter.category %>
  </p>
  <span class="comments">
    <label for="comments"> User Comments</label>
    <% @comments.each do |comment| %>
      <h1><%= comment.title %></h1>
      <h2><%= comment.body %></h2>
    <% end %>
  </span>

  <%= link_to 'Add a Comment', new_chapter_comment_path(@chapter.id) %>
  <% if @current_user == session[:user_id] %>
  <%= link_to 'Delete Chapter', chapter_path(@chapter.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Edit', edit_saga_chapter_path(@chapter.saga_id, @chapter) %> |
  <% end %>
  <%= link_to 'Back', user_path(session[:user_id]) %>
</section>