config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]

  resources :comments

  resources :chapters

  resources :sagas

  resources :users

    resources :sagas do
      resources :chapters
    end

  resources :chapters do
    resources :comments
  end

end

app/models/saga.rb
class Saga < ActiveRecord::Base
  belongs_to :user
  has_many :chapters
end

app/controllers/sagas_controller.rb
class SagasController < ApplicationController
  before_action :set_saga, only: [:show, :edit, :update, :destroy]

  # GET /sagas
  # GET /sagas.json
  def index
    @sagas = Saga.all
  end

  # GET /sagas/1
  # GET /sagas/1.json
  def show
    @saga = Saga.find(params[:id])
    @chapters = Chapter.where("saga_id = ?", params[:id])
  end

  # GET /sagas/new
  def new
    @saga = Saga.new
  end

  # GET /sagas/1/edit
  def edit
  end

  # POST /sagas
  # POST /sagas.json
  def create
    @saga = Saga.create(title: params[:saga][:title], user_id: session[:user_id])
    redirect_to(user_path(session[:user_id]))
  end

  # PATCH/PUT /sagas/1
  # PATCH/PUT /sagas/1.json
  def update
    @saga.update(saga_params)
    redirect_to saga_path(params[:id])
  end

  # DELETE /sagas/1
  # DELETE /sagas/1.json
  def destroy
    @saga.destroy
    redirect_to user_path(session[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saga
      @saga = Saga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saga_params
      params.require(:saga).permit(:title, :user_id)
    end
end

app/helpers/sagas_helper.rb
module SagasHelper
end

app/views/sagas/_form.html.erb
<%= form_for(@saga) do |f| %>
  <% if @saga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saga.errors.count, "error") %> prohibited this saga from being saved:</h2>

      <ul>
      <% @saga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sagas/edit.html.erb
<section class="main">
	<h1>Editing saga</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @saga %> |
	<%= link_to 'Back', sagas_path %>
</section>

app/views/sagas/index.html.erb
<section class="main">
  <h1>Listing sagas</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sagas.each do |saga| %>
        <tr>
          <td><%= saga.title %></td>
          <td><%= saga.user %></td>
          <td><%= link_to 'Show', saga %></td>
          <td><%= link_to 'Edit', edit_saga_path(saga) %></td>
          <td><%= link_to 'Destroy', saga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Saga', new_saga_path %>
</section>

app/views/sagas/new.html.erb
<section class="main">
	<h1>New saga</h1>

	<%= render 'form' %>

	<%= link_to 'Back', user_path(session[:user_id]) %>
</section>

app/views/sagas/show.html.erb
<section class="main">
	<p id="notice"><%= notice %></p>


	  <strong>Title:</strong> <%= @saga.title %>


	</p>

	<p>
	  <% @chapters.each do |chapter| %>
	  <ul>
	  	<li>
	  		<tbody>
	  			<tr>
	  				<td>
	  					<%= link_to(chapter.title, chapter_path(chapter.id)) %>
	  				</td>
	  				<td>
                        <%= chapter.scope %>
	  				</td>
	  			</tr>
	  		</tbody>
	  	</li>
	  </ul>
	  <% end %>
	</p>
	<% if @saga.user_id == session[:user_id] %>
	<%= link_to 'Add a Chapter', new_saga_chapter_path(@saga) %> |
	<%= link_to 'Edit', edit_saga_path(@saga) %>
	<%= link_to 'Destroy', saga_path(@saga.id), method: :delete, data: { confirm: 'Are you sure?' } %> |

	<%= link_to 'back', user_path(session[:user_id]) %>

	<% else %>

	<%= link_to 'back', user_path(@saga.user_id) %>

	<% end %>
</section>